language: python

python:
  - 3.6

install: 
  "pip install -r requirements.txt"
  - git clone https://github.com/Cadair/ablog.git

before_script: ablog build

script: make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $mytoken
  local_dir: build/html/
  on:
    branch: master